---
fontsize: 12pt

latex-before-packages-includes:

latex-after-packages-includes:
- \usepackage{pdflscape}
- \makeatletter\renewcommand{\@biblabel}[1]{\quad#1.}\makeatother

# Internationalization
- \usepackage{fontspec}
- \usepackage{polyglossia}
- \setmainlanguage{english}
- \setotherlanguage{ukrainian}
- \newfontfamily\cyrillicfont[Script=Cyrillic]{CMU Serif}
- \newfontfamily\cyrillicfontsf[Script=Cyrillic]{CMU Sans Serif}
- \newfontfamily\cyrillicfonttt[Script=Cyrillic]{CMU Typewriter Text}

latex-header-includes:

biblio-style: alpha
natbib-options:
- numbers
- sort&compress
---
